global:
  scrape_interval: 15s  # Default interval to scrape targets.

scrape_configs:
  - job_name: 'ai-artistic-style-service'
    static_configs:
      - targets: ['host.docker.internal:5001']
  - job_name: 'prometheus'
    static_configs:
      - targets: ['host.docker.internal:9090']
